name: Deploy Frontend to S3

on:
  push:
    paths:
    - 'client/**'
    branches:
      - main

jobs:
  deploy-front-end-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build
        run: CI=false npm run build
        working-directory: ./client

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to S3
        run: aws s3 sync ./client/build/ s3://cyf-applysmart